### ISSUE TITLE
ПАШИ СУКА feature

### ISSUE THREAD

**Issue by leanton** [leanton/itbot#1]
Чтоб на фразу "не пашет" отвечал "ПАШИ СУКА"

**Comment by leanton** [comment]
@ishalyminov done

**Comment by ishalyminov** [comment]
@leanton супер, как его попробовать из телеграма?)

**Comment by leanton** [comment]
@ishalyminov https://telegram.me/itsupport_bot

**Comment by ishalyminov** [comment]
@leanton Всё ещё молчит
